# .github/workflows/build.yml
name: Build and Package FocusTimer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build fat JAR
        run: ./gradlew clean shadowJar
        shell: bash

      - name: Upload JAR artifact
        # <-- 여기만 @v3 에서 @v2 로 바꿨습니다
        uses: actions/upload-artifact@v2
        with:
          name: FocusTimer-JAR
          path: build/libs/*.jar
