# .github/workflows/build.yml
name: Build and Package FocusTimer

# main 브랜치에 푸시될 때마다 실행
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. 소스 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. JDK 17 세팅
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Gradle 빌드 (fat-jar 생성)
      - name: Build fat JAR
        run: ./gradlew clean build

      # 4. jpackage 로 EXE 패키징
      - name: Package EXE with jpackage
        run: |
          jpackage \
            --type exe \
            --name FocusTimer \
            --app-version 1.0 \
            --input build/libs \
            --main-jar FocusTimer-all.jar \
            --main-class TimerApp \
            --win-shortcut \
            --win-menu \
            --dest installer-output

      # 5. 빌드 산출물(인스톨러) 업로드
      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: FocusTimer-installer
          path: installer-output
