name: Build and Package FocusTimer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 체크아웃 소스코드
        uses: actions/checkout@v3

      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: fat JAR 빌드
        run: ./gradlew shadowJar

      - name: EXE 패키징
        run: |
          jpackage `
            --type exe `
            --name FocusTimer `
            --app-version 1.0 `
            --input build/libs `
            --main-jar FocusTimer-all.jar `
            --main-class TimerApp `
            --icon path/to/icon.ico `
            --win-shortcut `
            --win-menu `
            --module-path "C:\javafx-sdk-17.0.15\lib" `
            --add-modules javafx.controls

      - name: installer 업로드
        uses: actions/upload-artifact@v3
        with:
          name: FocusTimer-installer
          path: installer-output/FocusTimer
