# .github/workflows/build.yml
name: Build and Package FocusTimer

# main 브랜치에 Push 될 때마다 실행
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) 소스 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) JDK 17 설치
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3) Gradle 빌드
      - name: Build with Gradle
        run: |
          ./gradlew clean build

      # 4) fat JAR 생성 (build/libs/FocusTimer-all-1.0.jar)
      - name: Create fat JAR
        run: |
          ./gradlew jar

      # 5) jpackage로 EXE 패키징
      - name: Package EXE with jpackage
        run: |
          jpackage `
            --type exe `
            --name FocusTimer `
            --app-version 1.0 `
            --input build/libs `
            --main-jar FocusTimer-all-1.0.jar `
            --main-class TimerApp `
            --win-shortcut `
            --win-menu `
            --dest installer-output

      # 6) 생성된 installer-output 폴더를 Artifact로 업로드
      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          name: FocusTimer-installer
          path: installer-output/
