name: Build and Package FocusTimer

on:
  push:
    tags:
      - 'v*.*.*'    # v1.0.0 형태로 태그를 푸시할 때만 실행

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build fat JAR
      run: .\gradlew.bat clean fatJar

    - name: Create custom runtime image via jlink
      run: |
        jlink ^
          --module-path "%JAVA_HOME%\jmods;C:\javafx-sdk-17.0.15\lib" ^
          --add-modules java.base,java.desktop,javafx.controls ^
          --output custom-runtime

    - name: Package EXE with jpackage
      run: |
        jpackage ^
          --type exe ^
          --name FocusTimer ^
          --app-version ${{ github.ref_name }} ^
          --input build\libs ^
          --main-jar FocusTimer-all.jar ^
          --main-class TimerApp ^
          --win-shortcut ^
          --win-menu ^
          --runtime-image custom-runtime

    - name: Upload installer artifact
      uses: actions/upload-artifact@v3
      with:
        name: FocusTimer-Installer
        path: '*.exe'
